#ifdef SINGLE_PRECISION
#define MYKIND kind(1.0)
#define EULERCENTRAL_THREADS_X 128
#define EULERCENTRAL_THREADS_Y 3
#define EULERWENO_THREADS_X 128
#define EULERWENO_THREADS_Y 2
#else
#define MYKIND kind(1.d0)
#define EULERCENTRAL_THREADS_X 128
#define EULERCENTRAL_THREADS_Y 3
#define EULERWENO_THREADS_X 128
#define EULERWENO_THREADS_Y 2
#endif

